# Generated by Django 5.2.6 on 2025-09-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_rename_productos_producto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='productos_db',
        ),
    ]
