# Generated by Django 5.2.6 on 2025-09-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_alter_producto_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='producto_producto',
        ),
    ]
