# Generated by Django 5.2.6 on 2025-10-02 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0005_pedidoreabastecimiento'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedidoreabastecimiento',
            table='pedido_reabastecimiento',
        ),
    ]
