# Generated by Django 5.2.6 on 2025-10-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0006_alter_pedidoreabastecimiento_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
